/**
 * Curated Lucide icon set for agent/entity icon pickers.
 * ~60 icons covering agents, engineering, data, ops, creative, business, communication, and more.
 */
import {
  Activity,
  Anchor,
  Aperture,
  Archive,
  BarChart3,
  Battery,
  Bell,
  Bluetooth,
  Bolt,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Bug,
  Calendar,
  Camera,
  Clapperboard,
  Clock3,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cpu,
  Crown,
  Database,
  Diamond,
  Disc,
  DollarSign,
  Droplets,
  Eye,
  Feather,
  FileText,
  Film,
  Fingerprint,
  Flame,
  FlaskConical,
  Folder,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  Globe,
  Hammer,
  Handshake,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  Image,
  Inbox,
  Key,
  Lamp,
  Layers,
  Layout,
  Lightbulb,
  Link,
  type LucideIcon,
  Lock,
  Mail,
  Map as MapIcon,
  Megaphone,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Navigation,
  Network,
  Package,
  Paintbrush,
  Palette,
  PenTool,
  Percent,
  Phone,
  Plane,
  Plug,
  Podcast,
  Printer,
  Puzzle,
  Radio,
  Rocket,
  Ruler,
  Satellite,
  Scale,
  Scissors,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Ship,
  ShoppingCart,
  Skull,
  Slack,
  Smartphone,
  Sparkles,
  Speaker,
  Star,
  Sun,
  Sword,
  Syringe,
  Target,
  Telescope,
  Terminal,
  TestTube,
  Thermometer,
  Timer,
  Tornado,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Users,
  Wand2,
  Watch,
  Wifi,
  Wind,
  Wrench,
  Zap,
} from "lucide-react";

export type IconOption = { value: string; label: string; icon: LucideIcon; keywords: string[] };

export const LUCIDE_ICON_OPTIONS: IconOption[] = [
  // Agents & AI
  { value: "bot", label: "Robot", icon: Bot, keywords: ["agent", "ai", "worker", "assistant"] },
  { value: "brain", label: "Brain", icon: Brain, keywords: ["ai", "intelligence", "thinking", "model"] },
  { value: "sparkles", label: "Sparkles", icon: Sparkles, keywords: ["ai", "magic", "generate"] },
  { value: "wand", label: "Wand", icon: Wand2, keywords: ["magic", "wizard", "generate"] },
  { value: "cpu", label: "CPU", icon: Cpu, keywords: ["compute", "processor", "infra", "hardware"] },
  { value: "network", label: "Network", icon: Network, keywords: ["nodes", "mesh", "distributed"] },

  // Energy & Speed
  { value: "zap", label: "Lightning", icon: Zap, keywords: ["speed", "ceo", "energy", "fast", "power"] },
  { value: "bolt", label: "Bolt", icon: Bolt, keywords: ["power", "electric"] },
  { value: "flame", label: "Flame", icon: Flame, keywords: ["fire", "hot", "urgent", "trending"] },
  { value: "rocket", label: "Rocket", icon: Rocket, keywords: ["launch", "ship", "build", "fast"] },
  { value: "gauge", label: "Gauge", icon: Gauge, keywords: ["speed", "performance", "meter"] },
  { value: "timer", label: "Timer", icon: Timer, keywords: ["clock", "deadline", "speed"] },
  { value: "activity", label: "Activity", icon: Activity, keywords: ["pulse", "heartbeat", "health"] },

  // Security & Trust
  { value: "shield", label: "Shield", icon: Shield, keywords: ["security", "guard", "trust", "defense"] },
  { value: "lock", label: "Lock", icon: Lock, keywords: ["secure", "auth", "password", "private"] },
  { value: "key", label: "Key", icon: Key, keywords: ["access", "auth", "credential"] },
  { value: "fingerprint", label: "Fingerprint", icon: Fingerprint, keywords: ["identity", "biometric", "auth"] },
  { value: "eye", label: "Eye", icon: Eye, keywords: ["watch", "observe", "monitor", "vigilant"] },
  { value: "skull", label: "Skull", icon: Skull, keywords: ["danger", "hacker", "security"] },

  // Engineering & Code
  { value: "terminal", label: "Terminal", icon: Terminal, keywords: ["code", "software", "dev", "cli"] },
  { value: "code", label: "Code", icon: Code, keywords: ["full-stack", "programming", "brackets"] },
  { value: "git-branch", label: "Git", icon: GitBranch, keywords: ["version", "branch", "repo"] },
  { value: "bug", label: "Bug", icon: Bug, keywords: ["debug", "testing", "qa", "issue"] },
  { value: "wrench", label: "Wrench", icon: Wrench, keywords: ["engineering", "backend", "ops", "fix"] },
  { value: "hammer", label: "Hammer", icon: Hammer, keywords: ["build", "construct", "tool"] },
  { value: "settings", label: "Gear", icon: Settings, keywords: ["config", "settings", "ops", "system"] },
  { value: "plug", label: "Plug", icon: Plug, keywords: ["connect", "integration", "api"] },
  { value: "server", label: "Server", icon: Server, keywords: ["infra", "backend", "hosting", "cloud"] },
  { value: "database", label: "Database", icon: Database, keywords: ["data", "storage", "sql", "db"] },
  { value: "layers", label: "Layers", icon: Layers, keywords: ["stack", "architecture", "depth"] },

  // Data & Analytics
  { value: "bar-chart", label: "Chart", icon: BarChart3, keywords: ["metrics", "data", "report", "analytics"] },
  { value: "trending-up", label: "Growth", icon: TrendingUp, keywords: ["analytics", "market", "profit"] },
  { value: "dollar", label: "Dollar", icon: DollarSign, keywords: ["money", "finance", "billing", "cost"] },
  { value: "percent", label: "Percent", icon: Percent, keywords: ["rate", "discount", "statistics"] },
  { value: "scale", label: "Scale", icon: Scale, keywords: ["balance", "legal", "justice", "weight"] },

  // Science & Research
  { value: "telescope", label: "Telescope", icon: Telescope, keywords: ["research", "scout", "explore", "observe"] },
  { value: "flask", label: "Flask", icon: FlaskConical, keywords: ["science", "chemistry", "experiment"] },
  { value: "test-tube", label: "Lab", icon: TestTube, keywords: ["test", "qa", "experiment", "science"] },
  { value: "compass", label: "Compass", icon: Compass, keywords: ["navigate", "direction", "explore"] },
  { value: "search", label: "Search", icon: Search, keywords: ["find", "lookup", "discover"] },
  { value: "satellite", label: "Satellite", icon: Satellite, keywords: ["space", "orbit", "signal"] },
  { value: "thermometer", label: "Thermometer", icon: Thermometer, keywords: ["temperature", "weather", "heat"] },

  // Design & Creative
  { value: "palette", label: "Palette", icon: Palette, keywords: ["frontend", "ui", "creative", "design", "color"] },
  { value: "layout", label: "Layout", icon: Layout, keywords: ["ux", "ui", "product", "wireframe", "screen"] },
  { value: "paintbrush", label: "Paintbrush", icon: Paintbrush, keywords: ["art", "draw", "design"] },
  { value: "pen-tool", label: "Pen", icon: PenTool, keywords: ["draw", "design", "vector"] },
  { value: "image", label: "Image", icon: Image, keywords: ["photo", "picture", "media"] },
  { value: "camera", label: "Camera", icon: Camera, keywords: ["photo", "capture", "visual"] },
  { value: "film", label: "Film", icon: Film, keywords: ["video", "movie", "media"] },
  { value: "scissors", label: "Scissors", icon: Scissors, keywords: ["cut", "edit", "trim"] },
  { value: "feather", label: "Feather", icon: Feather, keywords: ["write", "light", "quill"] },

  // Communication
  { value: "mail", label: "Mail", icon: Mail, keywords: ["email", "message", "inbox"] },
  { value: "message", label: "Message", icon: MessageSquare, keywords: ["chat", "comment", "talk"] },
  { value: "megaphone", label: "Megaphone", icon: Megaphone, keywords: ["announce", "marketing", "broadcast"] },
  { value: "bell", label: "Bell", icon: Bell, keywords: ["notification", "alert", "remind"] },
  { value: "phone", label: "Phone", icon: Phone, keywords: ["call", "contact", "mobile"] },
  { value: "mic", label: "Mic", icon: Mic, keywords: ["voice", "audio", "record", "podcast"] },
  { value: "headphones", label: "Headphones", icon: Headphones, keywords: ["audio", "music", "listen"] },
  { value: "radio", label: "Radio", icon: Radio, keywords: ["signal", "broadcast", "monitor"] },

  // Business & Organization
  { value: "briefcase", label: "Briefcase", icon: Briefcase, keywords: ["business", "work", "corporate"] },
  { value: "crown", label: "Crown", icon: Crown, keywords: ["leader", "ceo", "king", "premium"] },
  { value: "trophy", label: "Trophy", icon: Trophy, keywords: ["win", "achievement", "success"] },
  { value: "star", label: "Star", icon: Star, keywords: ["favorite", "important", "highlight"] },
  { value: "gem", label: "Gem", icon: Gem, keywords: ["premium", "valuable", "quality"] },
  { value: "diamond", label: "Diamond", icon: Diamond, keywords: ["premium", "luxury", "valuable"] },
  { value: "heart", label: "Heart", icon: Heart, keywords: ["love", "favorite", "health"] },
  { value: "handshake", label: "Handshake", icon: Handshake, keywords: ["deal", "partnership", "agreement"] },
  { value: "users", label: "Users", icon: Users, keywords: ["team", "people", "group", "org"] },

  // Navigation & Location
  { value: "globe", label: "Globe", icon: Globe, keywords: ["web", "network", "global", "world"] },
  { value: "map", label: "Map", icon: MapIcon, keywords: ["location", "navigate", "geography"] },
  { value: "navigation", label: "Navigate", icon: Navigation, keywords: ["direction", "pointer", "cursor"] },
  { value: "home", label: "Home", icon: Home, keywords: ["house", "main", "base"] },
  { value: "anchor", label: "Anchor", icon: Anchor, keywords: ["stable", "port", "maritime"] },
  { value: "mountain", label: "Mountain", icon: Mountain, keywords: ["peak", "climb", "outdoors"] },

  // Things & Objects
  { value: "monitor", label: "Monitor", icon: Monitor, keywords: ["display", "screen", "dashboard"] },
  { value: "package", label: "Package", icon: Package, keywords: ["product", "delivery", "bundle", "box"] },
  { value: "file-text", label: "Document", icon: FileText, keywords: ["docs", "writing", "content"] },
  { value: "book", label: "Book", icon: BookOpen, keywords: ["learn", "docs", "knowledge", "read"] },
  { value: "folder", label: "Folder", icon: Folder, keywords: ["organize", "directory", "files"] },
  { value: "lightbulb", label: "Lightbulb", icon: Lightbulb, keywords: ["idea", "innovation", "bright"] },
  { value: "target", label: "Target", icon: Target, keywords: ["focus", "goal", "precision", "aim"] },
  { value: "puzzle", label: "Puzzle", icon: Puzzle, keywords: ["solve", "integrate", "fit"] },
  { value: "link", label: "Link", icon: Link, keywords: ["connect", "chain", "url"] },
  { value: "cloud", label: "Cloud", icon: Cloud, keywords: ["hosting", "saas", "storage", "sky"] },
  { value: "umbrella", label: "Umbrella", icon: Umbrella, keywords: ["protect", "insurance", "cover"] },

  // Nature & Weather
  { value: "sun", label: "Sun", icon: Sun, keywords: ["day", "light", "bright", "weather"] },
  { value: "moon", label: "Moon", icon: Moon, keywords: ["night", "dark", "sleep"] },
  { value: "wind", label: "Wind", icon: Wind, keywords: ["air", "breeze", "weather"] },
  { value: "droplets", label: "Droplets", icon: Droplets, keywords: ["water", "rain", "liquid"] },
  { value: "tornado", label: "Tornado", icon: Tornado, keywords: ["storm", "chaos", "weather"] },
  { value: "coffee", label: "Coffee", icon: Coffee, keywords: ["break", "morning", "energy"] },
];

export const LUCIDE_ICON_MAP = new Map(LUCIDE_ICON_OPTIONS.map((o) => [o.value, o]));
